project_id = "local"

[functions.api]
verify_jwt = false

[functions.faucetpay-payouts]
verify_jwt = false

[functions.announce-worker]
verify_jwt = false

[functions.market-notify-worker]
verify_jwt = false
